# CMake generated Testfile for 
# Source directory: /home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch
# Build directory: /home/etftk/Downloads/ns-allinone-3.42/ns-3.42/cmake-cache/scratch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-scratch_Zadaca1_2217 "ns3.42-Zadaca1_2217-default")
set_tests_properties(ctest-scratch_Zadaca1_2217 PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_Zadatak3 "ns3.42-Zadatak3-default")
set_tests_properties(ctest-scratch_Zadatak3 PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_Zadatak3a "ns3.42-Zadatak3a-default")
set_tests_properties(ctest-scratch_Zadatak3a PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_Zadatak4 "ns3.42-Zadatak4-default")
set_tests_properties(ctest-scratch_Zadatak4 PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_first "ns3.42-first-default")
set_tests_properties(ctest-scratch_first PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_main-attribute-value "ns3.42-main-attribute-value-default")
set_tests_properties(ctest-scratch_main-attribute-value PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_main-grid-topology "ns3.42-main-grid-topology-default")
set_tests_properties(ctest-scratch_main-grid-topology PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_main-random-walk "ns3.42-main-random-walk-default")
set_tests_properties(ctest-scratch_main-random-walk PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_my_crypto_example "ns3.42-my_crypto_example-default")
set_tests_properties(ctest-scratch_my_crypto_example PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_ns2-mobility-trace "ns3.42-ns2-mobility-trace-default")
set_tests_properties(ctest-scratch_ns2-mobility-trace PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_sample-random-variable "ns3.42-sample-random-variable-default")
set_tests_properties(ctest-scratch_sample-random-variable PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_scratch-simulator "ns3.42-scratch-simulator-default")
set_tests_properties(ctest-scratch_scratch-simulator PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;79;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
add_test(ctest-scratch_subdir_scratch-subdir "ns3.42-scratch-subdir-default")
set_tests_properties(ctest-scratch_subdir_scratch-subdir PROPERTIES  WORKING_DIRECTORY "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build/scratch/subdir/" _BACKTRACE_TRIPLES "/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/build-support/custom-modules/ns3-executables.cmake;140;set_runtime_outputdirectory;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;67;build_exec;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;109;create_scratch;/home/etftk/Downloads/ns-allinone-3.42/ns-3.42/scratch/CMakeLists.txt;0;")
subdirs("nested-subdir")
